### ISSUE TITLE
call "processmessages"  on OnShow

### ISSUE THREAD

**Issue by drcrck** [andrea-magni/TFrameStand#11]
Hi!
in function TFrameInfo<T>.Show  can be useful to call application.processmessage if there's not a background task, just to "force" stand to be showed. 

 at the and , instead of 

<i>
[cut]
    ).Start;
  end;
end;
</i>

you can write : 
<i>
    ).Start;
  end
  else application.ProcessMessages ;
end;
</i>

**Comment by andrea-magni** [comment]
I think this should not be needed. Are (were) you experiencing problems without it?

Thanks (and sorry for the late)

**Comment by drcrck** [comment]
sometimes, if frame showing is for a little time, it not show it.  ( we'll talk about it next week )
