### ISSUE TITLE
layout problem with berlin.

### ISSUE THREAD

**Issue by drcrck** [andrea-magni/TFrameStand#12]
ciao andrea!
with new berlin style editor, root layout is always set to "center" , so is impossibble to allign a frame to contents or client.
should override it in framestand :)

**Comment by drcrck** [comment]
for my purpose i made this change:

  if not Assigned(FStand) then
  begin
    FStand := TLayout.Create(nil);
    FStand.StyleName := 'container';
  end;
  FStand.Align := TAlignLayout.Contents; //<--------------------   always 
  FStand.Visible := False;


but i suppose it'll better to add a TAlignLayout property to TFrameInfo

**Comment by Spelt** [comment]
I did submit a bug report. 
https://quality.embarcadero.com/browse/RSP-14806

**Comment by drcrck** [comment]
i think in berlin this issue con be response ad "Works As Expected" .... :(

**Comment by andrea-magni** [comment]
I've added the workaround even if I am not so happy with that because in my original thoughts, a developer could want to use any Align value on the stand.
I've voted the issue on the quality portal. Let's hope it get fixed ;-)

**Comment by foxdayk** [comment]
i use FrameStandFramesBeforeShow event so:
`    if (AFrameInfo.StandStyleName = 'filterframe') then
        LLayout := TLayout(AFrameInfo.Stand);
        if LLayout <> nil then LLayout.Align := TAlignLayout.MostLeft;
`
