### ISSUE TITLE
Target Android get Errors

### ISSUE THREAD

**Issue by rbrose** [andrea-magni/TFrameStand#13]
Hi,

i have install the TFrameStand with open FrameStandPackage.dproj and click on compile and then install.

If i have set target system Win32 FrameStand Unit will be found and i can start the application.
If i set target system to android i get error that FrameStand unit not found, also TFrameStand ist not found and TFrameInfo.

How i can make FrameStand on Android available?

**Comment by Spelt** [comment]
Hi

Your search path is not correct for Android?  note: you can set a global
search path for your project or for all projects. See:
http://docwiki.embarcadero.com/RADStudio/Berlin/en/Library

Hope it helps!



2016-06-14 22:16 GMT+02:00 rbrose <notifications@github.com>:

**Comment by rbrose** [comment]
Yes i have add sources path, and copy Frames.Test.dcu, FrameStand.dcu, FrameStand.Editors.dcu, FrameStand.Editors.Forms.Test.dcu and FrameStandPackage.dcp to "Studio\18.0\lib\android\debug\", "Studio\18.0\lib\android\debug\de" and "\Studio\18.0\lib\android\release", ""\Studio\18.0\lib\android\release\de"

But i get always the same error :-( 

![bildschirmfoto 2016-06-15 um 09 50 49](https://cloud.githubusercontent.com/assets/1026824/16072017/d368348c-32de-11e6-9628-f8befbc037e8.png)

**Comment by Spelt** [comment]
Looks like you want to add windows dcu's to your android project?


What I always do in *Project Options >> Delphi Compiler >> Target: All
platforms*:

*Output directory:*  .\$(Platform)\$(Config)
*Unit output directory:  *.\$(Platform)\$(Config)
*Search path: *relative path to source of TFrameStand. Can also be absolute
path.

This will find the sources and compile for the right platform.




2016-06-15 9:54 GMT+02:00 rbrose <notifications@github.com>:

**Comment by rbrose** [comment]
But this means i must compile the FrameStand component with android too?

**Comment by Spelt** [comment]
I do this with libraries but forgot that this is a component.

Did you add TFramestand with GetIt ?




2016-06-15 10:16 GMT+02:00 rbrose <notifications@github.com>:

**Comment by Spelt** [comment]
GetIt added in *Tools >> Options >> Delphi Options >> Libary >> Libray
path: *  $(BDSCatalogRepository)\TFrameStand-1.0\source\

2016-06-15 10:26 GMT+02:00 Edward Spelt <edwardspelt@gmail.com>:

**Comment by rbrose** [comment]
You i download this here in git. But it must work without GetIt too or?

**Comment by Spelt** [comment]
I you add it via GetIt It will just work.

2016-06-15 10:49 GMT+02:00 rbrose <notifications@github.com>:

**Comment by rbrose** [comment]
I can't connect GetIt Package Manager. Get Error 12029.

So i have find a way how add this component manually :-)

Must i compile die component for android too?

**Comment by Spelt** [comment]
12029 means cannot connect to the server. Maybe temporary a problem.  I
would just wait until it works.



2016-06-15 10:58 GMT+02:00 rbrose <notifications@github.com>:

**Comment by rbrose** [comment]
this URL ist right? http://getit.embarcadero.com/

I get there:

Not Found
The requested URL / was not found on this server.

**Comment by andrea-magni** [comment]
There is an "installation - manual"  section in the readme.md file. If you install manually, be sure to add the source folder to your library path (select the proper configuration at the top of the window)... 
If you use GetIt (simply open Tools - GetIt package manager, search for TFrameStand and click install), it will do everything automatically. 

Let me know! :-)

**Comment by rbrose** [comment]
Hi Andrea,

now is GetIt accessible and after install over GetIt, it works fine. Thank you!

btw. a another question. I have a MultiView and a listview in master panel. the listview is a menu. after click a menu entry, a TFrame will be load with FrameStand in the Layout content.

Now if i click another menu entry, i must check i another TFrameInfo exist, if yes i must hide and close it. and then create a new one and show.

Have FrameStand a function for Hide and close all exist Frames? So that i don't need check manual all open frames?

**Comment by andrea-magni** [comment]
Check the FrameInfos property of TFrameStand! 😉
It should fit your needs. 

Bye
