### ISSUE TITLE
Question: latest commit not in GetIt Package manager

### ISSUE THREAD

**Issue by Spelt** [andrea-magni/TFrameStand#14]
Hi Andrea

I was wondering if the [latest commit ](https://github.com/andrea-magni/TFrameStand/commit/78df8a29bdade04fe64c1309ae5799beb3b4a7e4) should be in the GetIt package manager. Seems important.

Thanks .

**Comment by andrea-magni** [comment]
Yes it should! I will submit a request to update the GetIt version as soon as I finish also a couple of other improvements

Thanks

**Comment by Spelt** [comment]
Ok thanks! Can you please post a reply here when an update is out?  :-)

btw many thanks for this component, it really helps a lot.

**Comment by andrea-magni** [comment]
http://www.andreamagni.eu/wp/2016/10/tframestand-v-1-2-available-on-github-and-getit/

:-)

**Comment by Spelt** [comment]
Thanks!
