### ISSUE TITLE
Using WebBrowse or TMapView in TFrameStand

### ISSUE THREAD

**Issue by medreis** [andrea-magni/TFrameStand#16]
Hello,

I'm trying to use the TFrameStand with Twebbrowse or TMapView.

When you run the application on windows or android error occurs.

Anyone know tell me if it is possible to use them with TFrame?

Thank you

Marcio Eduardo

**Comment by andrea-magni** [comment]
Hi, what errors? 
I suspect that TMapView and TWebBrowse will not behave well inside a TFrame (as any other native component) since Z-Order support is limited on mobile platforms, AFAIK.
I am not aware TMapView is supported on Windows platform.

**Comment by drcrck** [comment]
i made a simple app , and webbrowser is working without problem and with "good" z-order

**Comment by medreis** [comment]
Hi,

Using TMapView, is working OK, but it is not supported by Windows, but the use of the application is Mobile, so the use of TWebBrowser, if the application is in the windows, used TWebBrowser.

Using TWebBrowser the frame an error occurs "Error reading WebBroser1.Size.Width, access violation .... in Windows the error occurs. with form working fine.

I'm using Delphi Seattle, up1, not tested in other versions.

Thanks 

Marcio
![erro](https://cloud.githubusercontent.com/assets/9445893/19114716/95cbc242-8ae5-11e6-8c72-72dd00868a6b.jpg)

**Comment by medreis** [comment]
What version Dephi do you use ?
