### ISSUE TITLE
Find Frame in TFrameStand

### ISSUE THREAD

**Issue by medreis** [andrea-magni/TFrameStand#19]
Hello,

I use this code to create a Frame .
I need  to find if the Frame FFrameGraficoInfo  exist in  fPrincipal.FrameStand1,  
If it exists I do not create it again and only use it, but I could not identify the correct syntax for the operation.

How to check if the TGraficoFrame exists in TFrameStand ?

procedure TfPrincipal.RelatoriosExecute(Sender: TObject);
Var
      FFrameGraficoInfo : TFrameInfo<TGraficoFrame>;
begin

  FFrameGraficoInfo := fPrincipal.FrameStand1.New<TGraficoFrame>(Layout);
  dm.fdq_grafico.Active:= False;
  fPrincipal.ShowForm(FFrameGraficoInfo.Frame.Panel1);
  FFrameGraficoInfo.Show;

end;

**Comment by andrea-magni** [comment]
Hi, 
you can make FFrameGraficoInfo a (private or protected) member of your TfPrincipal class and create the instance only on demand:

if not Assigned(FFrameGraficoInfo) then
  FFrameGraficoInfo := FrameStand1.New<TGraficoFrame>(Layout);
(...)
FFrameGraficoInfo.Show;

this way, the frame(stand) will be created only once and then reused.

Hope this helps!

Sincerely,
Andrea

**Comment by medreis** [comment]
Hi,

In FrameGrafico I use

  private
    [FrameInfo] FInfo: TFrameInfo<TGraficoFrame>;

In the frame at the end of the operation I use  FInfo.Close   to free the memory, and not be several Frames created.

But with this I must also assigned nil to   fPrincipal.FFrameGraficoInfo := nil   otherwise error occurs  .

That is why I wanted to check the existence of the Class in the FrameStand, since the user can go to another operation and the Frame has not been finalized.

Marcio

**Comment by andrea-magni** [comment]
If you want to have a single instance of the frame (and stand) created on demand, you should not call FInfo.Close but instead FInfo.Hide.
This, and the check "if Assigned(FFrameGraficoInfo) then "  should be enough. (Why FInfo and not FFrameGraficoInfo ?).

If you still have doubts, feel free to attach a minimal example and I will try to have a look at.

Sincerely,
Andrea
