### ISSUE TITLE
OnHide animation not getting executed.

### ISSUE THREAD

**Issue by mchonan1996** [andrea-magni/TFrameStand#2]
The OnShow animation I have is working, however when the FFrameInfo.Hide() is getting called within the frame, the frame disappears without any animation. Yes I have set up the animation the exact same way I did with the onshow. Minimal bug but still. 

Great work by the way, loving it :)

**Comment by andrea-magni** [comment]
Hi, the TFrameInfo<T>.Hide method has a Delay argument.
You should pass in a proper value to give your OnHide* animations the time needed to run.
For example, if your animation lasts 1 second, you should call Hide(1000).
If you need to destroy (call Close) also, I would suggest to pass also the second argument that is an anonymous method that will be called once the hiding of the framestand has completed.

Have a look at the MaterialButton demo that has animations both OnShow and OnHide.

HTH and thanks for the kind words!

**Comment by mchonan1996** [comment]
My bad! Thought it was in seconds. Thanks a lot.

**Comment by andrea-magni** [comment]
Maybe it is my fault. FireMonkey uses seconds as unit of time (especially for TAnimation) but I am used to think in milliseconds (because of wide use of milliseconds as unit, for example in the Sleep function and similar)... I am not sure if I should change it or not. Will think about it. :-)
