### ISSUE TITLE
How to get current displayed frame ?

### ISSUE THREAD

**Issue by stephanewierzbicki** [andrea-magni/TFrameStand#22]
Hello,

I have an Android project where I'm using frames instead of forms. 
Structure is quite simple : 

- Login Frame
- Menu Frame
- Customer Frame
   - Customer detail frame

Only one frame can be visible at a time. All my frames does have OnkeyUp events declared. All frames are created with my maiin form as a parent.

How can I pass my main form keyevents to the current displayed frame ? I'm trying something like this... 

```
procedure TfrmMain.FormKeyUp(Sender: TObject; var Key: Word; var KeyChar: Char;
  Shift: TShiftState);
var
  frm:TFrame;
begin
   for frm in FrameStand1.FrameInfos.Keys.ToArray do
   if  frm.IsVisible then
    begin
    frm.OnKeyUp(Sender,Key,KeyChar,shift);
    break;
    end;
end;

```
But IsVisible is True for all my frame ! How to do it ?

**Comment by andrea-magni** [comment]
What if you check the IsVisible property of the FrameStand1.FrameInfos[x] ? 
The Frame (FrameInfos.Keys.ToArray is an array of TFrame items)  may have visible set to True but the corresponding Stand may have Visible to False and this leads to confusion (the Frame is not visible because it is inside the Stand)

**Comment by andrea-magni** [comment]
Here again I would use some sort of observer pattern from the form to the frames to propagate the KeyUp event.

**Comment by stephanewierzbicki** [comment]
You are right, using a sort of observer pattern is on my todo list.
Here is an updated version of my OnkeyUp event handler.

```
procedure TfrmMain.FormKeyUp(Sender: TObject; var Key: Word; var KeyChar: Char;
Shift: TShiftState);
var
  i: integer;
  frame: TFrame;
begin
  for i := high(FrameStand1.FrameInfos.Values.ToArray)
    downto low(FrameStand1.FrameInfos.Values.ToArray) do
    if (TFrameInfo<FMX.Forms.TFrame>(FrameStand1.FrameInfos.Values.ToArray[i])
      .Status = TFrameStatus.Visible) then
    begin
      frame := TFrameInfo<FMX.Forms.TFrame>
        (FrameStand1.FrameInfos.Values.ToArray[i]).frame;
      if assigned(frame) then
        if assigned(frame.OnKeyUp) then
          frame.OnKeyUp(Sender, Key, KeyChar, Shift);
      Key := 0;
      break;
    end;
end;
```
