### ISSUE TITLE
How to : create "dialogs" ?

### ISSUE THREAD

**Issue by stephanewierzbicki** [andrea-magni/TFrameStand#24]
I would like to mimic Android dialogs with TFrameStand. 

Is this possible to achieve this ? I have basic requirements, it would be : 
- modal buttons
- possibility to close (or not) the modal by tapping on the "dimmed" background.

What do you think ?

**Comment by andrea-magni** [comment]
Hi, sorry for the late.
Have a look a the Dialog demo I just pushed.

There are a couple of things to keep in mind:

1) I have recently widened the binding of common actions to TControl (before was only considering TButton and descendants) so if you are using the GetIt version you will need to keep line 69 of Forms.Main.pas:
`(FColorDialog.Stand.FindStyleResource('background_cancel') as TRectangle).OnClick := DoCancelColorDialog;`
If you are using the (latest) GitHub version, you can comment it out.

2) you should not think about modal dialogs in mobile applications. What I am doing here is defining a couple of anonymous methods that will be called once the user selects a color from a list or cancel (using the button or clicking on the stand, as you required) the dialog.
Obviously the code is non-blocking so keep that in mind while developing your app.

3) Also with respect to one question from you, I am thinking about implementing a mechanism to communicate from frames to the FrameStand (or to the form or to other frames). I think I will use the System.Messaging functionalities to implement this (soon, I hope).

If something is not clear, please reply here and I will try to explain better.

**Comment by stephanewierzbicki** [comment]
Thank you. I will look at the Dialog demo. It perfectly suits my needs
