### ISSUE TITLE
TFrameStand parenting "issues"

### ISSUE THREAD

**Issue by stephanewierzbicki** [andrea-magni/TFrameStand#25]
Hello,

I've tried to create a dynamic "wait frame" but it failed as soon as the frame is created.
It appears that TFrameStand parent can't be set to nil and must be a TFmxObject.

I've also tried to put my TFrameStand on a TDatamodule and set it's DefaultParent property to my main form. Frame were correctly created, displayed but there were a lot of memory leaks when closing my application (appears that all created frames were not correctly freed).

The only remaining solution is to put TFrameStand on a form.

Is there a way to change the GetDefaultParent method ? Is it possible to automatically set the DefaultParent with the 1st available visible form ? Right now, my "business" class does have the "form.main" unit and call my wait frame from here.... It will be better to separate my user interface unit from my business unit.

Best regards

**Comment by andrea-magni** [comment]
Hi,
I have projects where TFrameStand is on a TDataModule without problems. Maybe you are no calling Close for your TFrameInfo<TFrame> instances?
The TFrameStand component holds a list of active TFrameInfo<TFrame> and this may cause TFrame instances to last till the component (TFrameStand) destruction...

Your application logic should ask UI to reflect a "waiting status" before starting a long operation and close it when the operation is completed.

If you dare, you can send me a minimal project with your issues and I will try to help you.

Thanks,

**Comment by stephanewierzbicki** [comment]
Hi Andrea,

I'll prepare a minimal project with my issues. 
Should I sent the project here ?

Anyway, thank you for your kind help.

**Comment by andrea-magni** [comment]
You can drop me a link to Dropbox (or similar) here or via email: name(dot)surname(at)gmail(dot)com

You are welcome ;-)

**Comment by andrea-magni** [comment]
Hi @stephanewierzbicki,
I can't remember if we actually addressed this and solved it out...
I apologize if I missed something about this. Please re-open the issue if it is still standing and I'll try to sort it out...

**Comment by foxdayk** [comment]
When you destroy TSubjectStand, its Destroy event is fired, in which FCommonActions and FResponsive should be destroyed.
But if you added a handler of the type FrameStand.CommonActions.Add ('Close *', procedure ...), then when you call FreeAndNil (FCommonActions), an exception is thrown.
