### ISSUE TITLE
Delphi Tokyo :  android application crash with 'Can not activate current context' exception

### ISSUE THREAD

**Issue by stephanewierzbicki** [andrea-magni/TFrameStand#26]
Hi,

My Android (4.4.2) application is crashing with 'Can not activate current context' exception.
This is only happening when compiling it under Delphi Tokyo.

I have attached a sample project that reproduce my problem.

[TFrameStand crash.zip](https://github.com/andrea-magni/TFrameStand/files/872992/TFrameStand.crash.zip)

**Comment by stephanewierzbicki** [comment]
Could this be related ?
https://quality.embarcadero.com/browse/RSP-17636

**Comment by andrea-magni** [comment]
Hi Stephane, I've just tried your sample application but it does not crash on my device. I had to comment uses of FMX.DeviceInfo in Datamodule.Main.pas to compile...
However, I can see a different behavior on mobile wrt Desktop (Win32): the GlyphLogin object on frLogin is not being showed on mobile (but no visible errors).

I am using a Nexus 5X with Android 7.1.1, what's your environment?

Sincerely

**Comment by stephanewierzbicki** [comment]
Hi Andréa,

I am using a Symbol MC32N0 device (ex Motorola). It is running under Android 4.4.2.
SDK Build tools: 25.0.2
SDK API: 16
NDK API: 14
JDK: 1.8.0_66

This is surely related with the new TBitmap threading compatibility....

**Comment by andrea-magni** [comment]
I have used TFrameStand with Tokyo on Android for a while and I really think this is not related to TFrameStand itself, so I am closing this issue. 
Thanks!
