### ISSUE TITLE
Main form loses focus

### ISSUE THREAD

**Issue by EndErr** [andrea-magni/TFrameStand#27]
I'm using TFrameStand to create a application wizzard like with a main form and frames changing dynamicaly.
But when I add a frame the main form loses focus and can not click on system buttons (minimize, maximize, close).
The code I am using is from samples exept I free the frames in OnAfterHide event from TFrameStand.

**Comment by EndErr** [comment]
Any answer?

**Comment by andrea-magni** [comment]
The behavior you are describing happens when you free TFrameInfo<> too soon (i.e. transitions still running or similar). Would you please provide a simple project or piece of code showing the problem?

Thanks (sorry for the late)

**Comment by EndErr** [comment]
Bellow is a part of my code for MainForm.
After displaying a frame nearly everything is not accessible/focus-able/changeable (for example: main form border icons, drop lists from comboboxes) but buttons and edits are ok. The strange thing is that after a click in a edit or on a button those controls/actions are accessible/focus-able/changeable as it should be.

`unit uFrmMain;
interface
uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.Layouts, FireDAC.Phys.FBDef, FireDAC.Stan.Intf, FireDAC.Phys, FireDAC.Phys.IBBase, FireDAC.Phys.FB, FMX.DialogService, FrameStand, uFrLogin, uFrWelcome, uFrActions,uFrSettings;
type
  TAppState = (asLogin = 1, asWelcome = 2, asConfig = 6, asAppClose = 7, asInAction = 8);
  TfrmMain = class(TForm)
    laMainContent: TLayout;
    frMain: TFrameStand;
    procedure FormCreate(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure frMainAfterHide(const ASender: TFrameStand;
      const AFrameInfo: TFrameInfo<FMX.Forms.TFrame>);
    procedure FormDestroy(Sender: TObject);
  private
    { Private declarations }
    FLoginFrameInfo: TFrameInfo<TfrLogin>;
    FWelcomeFrameInfo: TFrameInfo<TfrWelcome>;
    FActionsFrameInfo: TFrameInfo<TfrActions>;
    FConfigFrame: TFrameInfo<TfrSettings>;
    FLoginResult: Byte;
    FWelcomeNextStep: Byte;
    FAppState: TAppState;
    procedure DestroyLoginFrame;
    procedure DestroyWelcomeFrame;
    procedure DestroyActionsFrame;
    procedure DestroyConfigFrame;
    procedure SetAppState(const Value: TAppState);
    procedure ClearFrames;
  protected
    function GetLoginFrame: TFrameInfo<TfrLogin>;
    property LoginFrameInfo: TFrameInfo<TfrLogin> read GetLoginFrame;
    function GetWelcomeFrame: TFrameInfo<TfrWelcome>;
    property WelcomeFrameInfo: TFrameInfo<TfrWelcome> read GetWelcomeFrame;
    function GetActionsFrame: TFrameInfo<TfrActions>;
    property ActionsFrameInfo: TFrameInfo<TfrActions> read GetActionsFrame;
    function GetConfigFrame: TFrameInfo<TfrSettings>;
    property ConfigFrame: TFrameInfo<TfrSettings> read GetConfigFrame;
  public
    { Public declarations }
    property AppState: TAppState read FAppState write SetAppState;
  end;
var
  frmMain: TfrmMain;
implementation
{$R *.fmx}
procedure TfrmMain.ClearFrames;
begin
  DestroyLoginFrame;
  DestroyWelcomeFrame;
  DestroyActionsFrame;
  DestroyConfigFrame;
end;
procedure TfrmMain.DestroyActionsFrame;
begin
  if Assigned(FActionsFrameInfo) then
  begin
    try
      if FActionsFrameInfo.IsVisible then
        FActionsFrameInfo.Hide;
      if Assigned(FActionsFrameInfo.Frame) then
        FActionsFrameInfo.Frame.CleanFrame;
      if Assigned(FActionsFrameInfo) then
        FActionsFrameInfo.Close;
    finally
      FActionsFrameInfo := nil;
    end;
  end;
end;
procedure TfrmMain.DestroyConfigFrame;
begin
  if Assigned(FConfigFrame) then
  begin
    try
      if FConfigFrame.IsVisible then
        FConfigFrame.Hide;
      if Assigned(FConfigFrame) then
        FConfigFrame.Close;
    finally          
      FConfigFrame := nil
    end  
  end;
end;
procedure TfrmMain.DestroyLoginFrame;
begin
  if Assigned(FLoginFrameInfo) then
  begin
    try
      if FLoginFrameInfo.IsVisible then
        FLoginFrameInfo.Hide;
      if Assigned(FLoginFrameInfo) then
        FLoginFrameInfo.Close;
    finally    
      FLoginFrameInfo := nil
    end  
  end;
end;
procedure TfrmMain.DestroyWelcomeFrame;
begin
  if Assigned(FWelcomeFrameInfo) then
  begin
    try
      if FWelcomeFrameInfo.IsVisible then
        FWelcomeFrameInfo.Hide;
      if Assigned(FWelcomeFrameInfo) then
        FWelcomeFrameInfo.Close;
    finally    
      FWelcomeFrameInfo := nil
    end  
  end;
end;
procedure TfrmMain.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  ClearFrames;
  Action := TCloseAction.caFree
end;
procedure TfrmMain.FormCreate(Sender: TObject);
begin
  FLoginResult := 0;
  FWelcomeNextStep := 0;
end;
procedure TfrmMain.FormDestroy(Sender: TObject);
begin
  ClearFrames
end;
procedure TfrmMain.FormShow(Sender: TObject);
begin
  AppState := asLogin
end;
procedure TfrmMain.frMainAfterHide(const ASender: TFrameStand;
  const AFrameInfo: TFrameInfo<FMX.Forms.TFrame>);
begin
  case FAppState of
    asLogin: begin
      if FLoginResult = 1 then
        AppState := asWelcome
      else
        AppState := asAppClose;
    end;
    asWelcome: begin
      case FWelcomeNextStep of
        1: AppState := asOpStart;
        2: AppState := asInAction;
        else AppState := asAppClose;
      end;
    end;
    asConfig: ;
    asAppClose: ;
    asInAction: ;
  end;
end;
function TfrmMain.GetActionsFrame: TFrameInfo<TfrActions>;
begin
  if not Assigned(FActionsFrameInfo) then
  begin
    FActionsFrameInfo := frMain.New<TfrActions>(laMainContent);
    FActionsFrameInfo.Frame.onSettings :=
      procedure
      begin
        FActionsFrameInfo.Hide;
        AppState := asConfig;
      end;
  end;
  Result := FActionsFrameInfo;
end;
function TfrmMain.GetConfigFrame: TFrameInfo<TfrSettings>;
begin
  if not Assigned(FConfigFrame) then
  begin
    FConfigFrame := frMain.New<TfrSettings>(laMainContent);
    FConfigFrame.Frame.onNextStep :=
      procedure
      begin
        FConfigFrame.Hide;
        AppState := asInAction;
      end;
  end;
  Result := FConfigFrame;
end;
function TfrmMain.GetLoginFrame: TFrameInfo<TfrLogin>;
begin
  if not Assigned(FLoginFrameInfo) then
  begin
    FLoginFrameInfo := frMain.New<TfrLogin>(laMainContent);
    FLoginFrameInfo.Frame.OnErrorLogIn :=
      procedure
      begin
        FLoginResult := 0;
        FLoginFrameInfo.Hide;
      end;
    FLoginFrameInfo.Frame.OnLogedIn :=
      procedure
      begin
        FLoginResult := 1;
        FLoginFrameInfo.Hide;
      end;
  end;
  Result := FLoginFrameInfo;
end;
function TfrmMain.GetWelcomeFrame: TFrameInfo<TfrWelcome>;
begin
  if not Assigned(FWelcomeFrameInfo) then
  begin
    FWelcomeFrameInfo := frMain.New<TfrWelcome>(laMainContent);
    FWelcomeFrameInfo.Frame.onNextStep :=
      procedure
      begin
        FWelcomeNextStep := FWelcomeFrameInfo.Frame.NextStepValue;
        FWelcomeFrameInfo.Hide;
      end;
  end;
  Result := FWelcomeFrameInfo;
end;
procedure TfrmMain.SetAppState(const Value: TAppState);
begin
  ClearFrames;
  FAppState := Value;
  case FAppState of
    asLogin: begin
	  LoginFrameInfo.Show();
    end;
    asWelcome: begin
      WelcomeFrameInfo.Show();
    end;
    asConfig: begin
      SetBackground('BG2');
      ConfigFrame.Show();
      ConfigFrame.Frame.OnKeyDown := ConfigFrame.Frame.FrameKeyDown;
    end;
    asAppClose: begin
      Close
    end;
    asInAction: begin
      ActionsFrameInfo.Show();
    end;
  end;
end;
end.`

**Comment by EndErr** [comment]
In the previous post the code is plain, I try to attach it to make it clear to understand.
`
[MainForm.txt](https://github.com/andrea-magni/TFrameStand/files/1124377/MainForm.txt)

`

**Comment by EndErr** [comment]
Any solution or school I go back to pagecontrol?

**Comment by andrea-magni** [comment]
Please be patient, I will try to provide you a working example as soon as possible...

**Comment by andrea-magni** [comment]
Ok, please have a look at the Wizard/Simple demo I pushed a few minutes ago on this repository. 
There are two things you have to notice :
1) always wait for hide to complete before calling close on a frame(info) ;
2) I made use of TDelayedAction in the third frame in order not to close (thus destroy) a frame from within an event handler of a button on the frame itself

Let me know if this helps. I hope to find time for a more advanced example (including gestures and better transitions) but as you noticed I am a bit busy these weeks. 

Sincerely

**Comment by EndErr** [comment]
Thanks, seams very good, will report after test in my application.

**Comment by EndErr** [comment]
The example with wizard works fine. 
The only question now is how to (from where and when) call a Close function to close main form?
I've tried to call it from within ShowStep->FFrameInfo.Hide and from ShowNext before FFrameInfo := TFrameInfo<TFrame ..., but I get always Access Violation errors in FormClose.
Where do I need to put Close function that will close the main form?

**Comment by andrea-magni** [comment]
If you want to close the main form from within a frame that is shown on that same form, I would send a message (System.Messaging) to the main form asking to close itself. This way you should avoid freeing the form that is the host of the frame before the frame has finished every UI related code (i.e. button rendering and similar).

**Comment by EndErr** [comment]
That was how I've done. From within the frame I send a Finish message (declared in Create) and after that I call Close for the main form.
