### ISSUE TITLE
FrameStand.OnAfterHide

### ISSUE THREAD

**Issue by EndErr** [andrea-magni/TFrameStand#30]
Another issue I found on line 758 in FrameStand unit at
`        if Assigned(FrameStand) and Assigned(FrameStand.OnAfterHide) then
          FrameStand.OnAfterHide(FrameStand, TFrameInfo<TFrame>(Self));
`
I get AV error, even without OnAfterHide set up.

**Comment by andrea-magni** [comment]
I am not experiencing this, would you please provide a minimal project showing the issue?
