### ISSUE TITLE
Problem with BPL dependencies

### ISSUE THREAD

**Issue by ChristenBlom** [andrea-magni/TFrameStand#32]
Hi Andrea, I've developed a package that requires your FrameStandPackage_10_2.dcp package.
Sometimes when I open the IDE it raises the error: Component TFrameStand can't be registered by package FrameStandPackage_10_2_250.bpl because it has already been registered by package FrameStandPackage_10_2_250.bpl.

The solution to this problem would be to create two separated packages: One with the runtime code (FrameStandPackage_10_2_250.bpl) and a second one (dclFrameStandPackage_10_2_250.bpl) with the design time code.

Could you split your code in these two packages?

**Comment by andrea-magni** [comment]
Hi, your request is legit! I probably underestimated the need of separate packages because the most common use of TFrameStand is with mobile applications (usually monolithic apps).

I will try to split the package ASAP.
Thanks
