### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pacs** [andrea-magni/TFrameStand#36]
Can i use yout TFrameStand in Commerical Apps ? 
If Yes are there any requirements ? 
I could not find the LICENSE file on Github ? 
Awesome Component by the way 👍

**Comment by andrea-magni** [comment]
Yes, you are free to use TFrameStand also in commercial applications. A mention somewhere would be greatly appreciated but it is not mandatory.
I'll add a more clear license indication.

Thanks for the kind words!
Sincerely
