### ISSUE TITLE
AV on change between frames

### ISSUE THREAD

**Issue by EndErr** [andrea-magni/TFrameStand#37]
Hi, i was directed by Wizard example to create a one form app with dynamically loaded frames.
The problem is the moment when I need to "go" to a specific frame from within existing frame.
In other words, in Frame1 from a button action I set NextStept to be Frame2, the Frame2 is initialized (in ShowFrame and ShowNext from example) and also the Frame1 is freed, but the code returns to complete the button action from Frame1, but it is already destroyed. 
How to make it right, to go to a specific frame from within another frame and destroy the first one?

**Comment by vgartner** [comment]
Hi @EndErr , I think it would not be a good idea to control the next page from the current page. You actually should use the approach used on the example. All the wizards I've seen implement it this way. Remember that many times a wizard also has also a back button...
An idea: as you want to go to a specific page, you probably will need to know the current page, maybe you can do it by looking what is the current step and than you can decide what would be the next one.

**Comment by EndErr** [comment]
Thanks for the reply.
I use the example and the methods used there.
The problem is when from Frame1 I execute Step:=aStep2 or from Frame2 I do Step:=aStep1 (to send message queue to the main form), in some times I get AV, and it is found mostrly when try to use some memory managament tools like EurekaLog or Leakcheck or madExcept or any other. Without them - everything works fine. 
So maybe it them who are not working as expected in this configuration of work?

**Comment by andrea-magni** [comment]
Hi @EndErr ,
would you please confirm this is an actual issue and still standing?

**Comment by EndErr** [comment]
Actually it was fixed with the delay on buttons click.
Thanks.
