### ISSUE TITLE
Get Top Frame

### ISSUE THREAD

**Issue by devzonetrack** [andrea-magni/TFrameStand#38]
When keyback hardware pressed top of frame close? how i can get top of frame and close it?

**Comment by andrea-magni** [comment]
TFrameStand holds a list of currently available TFrameInfo<> (see FrameInfos property).
The concept of "top of frame" is hard to define (last created frame? last shown frame?) but you can keep a reference to the corresponding TFrameInfo<TFrame> and use it to close that FrameInfo when you recognize a hardware back pressure (I usually handle this on the form OnKeyPress).

HTH

**Comment by andrea-magni** [comment]
Thanks @littleearth , I just merged your changes.
I am going to rename your OpenFrames to something like VisibleFrames and possibly provide a way to go from the Frame to the FrameInfo.
Check out next couple of commits.

Thanks for contributing to this project!
