### ISSUE TITLE
FrameStand kills animation other than OnShow*, etc

### ISSUE THREAD

**Issue by jkour** [andrea-magni/TFrameStand#40]
I think FrameStand does not allow any other animation in a frame to fire.

In particular, I am experiencing it with FMXLoading component.

When I put a loading image in a frame the animation does not work

**Comment by andrea-magni** [comment]
Hi @jkour,
would you please confirm this is still a issue? And that is actually tied to TFrameStand?

**Comment by andrea-magni** [comment]
I am closing the issue. Please reopen it if you still have troubles, thanks
