### ISSUE TITLE
TFramestand Rio - problem with big/long treatments ?

### ISSUE THREAD

**Issue by olivpadr** [andrea-magni/TFrameStand#41]
Hi

I have been using Dephi for almost 2 years and I installed the Rio version last week.

I noticed something weird on Android. I do not know if this is related to the changes of Android 9 - Pie (UI changes - View focus).

With the TframStand version 1.3 for Tokyo there is no problem.

I noticed that if there are big treatments that are launched the .

show of a frame do not work.

For you to check, I linked my project (Rio and Tokyo) : https://drive.google.com/drive/folders/1Hh4IhVR4_G9_2zTO08rCwpLT_g6ZivNK?usp=sharing

If you put 100000000 in the loop field, in the Tokyo version you will see the different frames display correctly. But with Rio we get the impression that it "freeze" because no frame is displayed.

I do not know if it's Rio the problem or if there is something wrong in my project or if there is something wrong with TFrameStand

Regards

**Comment by olivpadr** [comment]
Seems to be a "bug" on Rio 10.3 with the application.ProcessMessages (I opened RSP-22888 on quality.embarcadero.com)

**Comment by andrea-magni** [comment]
On one side I am relieved :-)
