### ISSUE TITLE
 Xe8?

### ISSUE THREAD

**Issue by dison2030** [andrea-magni/TFrameStand#5]
Hi, this work for xe8 or just for seattle?

**Comment by mchonan1996** [comment]
It works for both man. (:

**Comment by dison2030** [comment]
I get error FMX.ListView.Appearances don't exist on XE8

*Cortésmente,*


*Ing. Dison PeñaSoftware EngineerMobile | **Whatsapp: **1+ (809) 481-2430*

*GMT: (-4:00)*

*eMail: dison@dpsoftwares.com <dison@dpsoftwares.com>**Web:
**http://www.dpsoftwares.com
<http://www.dpsoftwares.com>*

**Comment by mchonan1996** [comment]
I'm pretty sure if you change the FMX.ListView.Appearances to be just FMX.ListView then you'll be good. 

There's also TListItems that it'll have (as far as I know) so you will need to make them TListViewItems instead. 

I haven't tested in XE8 but Andrea had said in his code rage session that it was compatible for XE8.

**Comment by andrea-magni** [comment]
Dison, please tell me what project fails to compile with XE8 (the package or one of the demo projects?)

Sincerely,
Andrea
