### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dhyanan73** [andrea-magni/TFrameStand#56]
Very poor documentation.

**Comment by checkdigits** [comment]
Are you asking for poor documentation or are you saying you'd like better documentation?

1. What areas would you like improved?
2. Have you watched any of the videos which show you how to use TFrameStand, there are quite a few?
3. Is there a specific thing you need help on?

Ian.

**Comment by dhyanan73** [comment]
I'd like better documentation. I've found only an old video about TFrameStand basic functionalities. Some demo projects no longer work. Nothing about TFormStand. Good documentation is a an exhaustive description of all methods and properties in writing (not only videos and demos), IMHO.

**Comment by andrea-magni** [comment]
Hi @dhyanan73, I am going to close this issue as AFAIK all demos are now working, there are demos addressing TFormStand and there's an entire chapter of my FMX book (Delphi GUI programming with Firemonkey, Packt) about TFrameStand. 
Feel free to open other issues if something is still missing.

Thanks,
Andrea
