### ISSUE TITLE
Wrong requires in dclFrameStandPackage_11.dpk

### ISSUE THREAD

**Issue by sbslavonac** [andrea-magni/TFrameStand#66]
Hi,
There is wrong requires in dclFrameStandPackage_11.dpk.

Instead of 
FrameStandPackage_10_4;
Should be
FrameStandPackage_11;

Regards
Boris

**Comment by andrea-magni** [comment]
Thanks, I just fixed the v.1.7 release.
Should work seamlessly with D11 Alexandria.
Please let me know of any problems.

Thanks
