### ISSUE TITLE
Delphi 11??

### ISSUE THREAD

**Issue by Aggie85** [andrea-magni/TFrameStand#67]
I tried compiling the TFrameStand package for Delphi 11 (after replacing the requirement 10_4 to 11).

Win32 run-time and design time build but the design package causes an eaccess error.

Has anyone gotten it to install and work properly?

All the best,

Shane

**Comment by andrea-magni** [comment]
I just released TFrameStand v.1.7, including Delphi 11 Alexandria support.
Please open other issues if you still encounter problems.

Thanks!
