### ISSUE TITLE
Access Violation when I try to close a Frame with TFrameStand

### ISSUE THREAD

**Issue by TheStranger25** [andrea-magni/TFrameStand#72]
Hi, I am developing a cross platform app through using TFrameStand but AccessViolation errors often occur.
I am using delphi 11.0 but these errors were also recurring in Delphi 10.3.
They occur, on each platform, when I try to close a frame through the following code:

```
   [FrameInfo]
   FI: TFrameInfo <TFScenariosEditor>;

[..]

   TDelayedAction.Execute (200, procedure
   begin
         FI Hide (0
         , procedure
           begin
             FI.Close
           end
         );
   end);
```

Running the app on Win32 and making use of the debugger, when these errors occur, the code hangs in the SubjectStand.pas at line 636 or at line 801

**Comment by andrea-magni** [comment]
Hi @TheStranger25 ,
I tried to reproduce this issue but with no success.
Here's attached a minimal example project that works fine (I tested Win32 only).

Let me know and feel free to reopen the issue is necessary.

Sincerely,
Andrea
