### ISSUE TITLE
[dcc64 Fatal Error] E2202 Required package 'DesignIDE' not found

### ISSUE THREAD

**Issue by antarey** [andrea-magni/TFrameStand#73]
Cannot compile for Win64

**Comment by andrea-magni** [comment]
I just checked and the WaitFrameStand demo compiles to Win64 with no issues.
Please provide steps to reproduce if this is still relevant.

Sincerely,
Andrea

**Comment by birbilis** [comment]
there is an issue with all your packages that GetIt brings. Only the dcl*.dproj ones should have the compiler parameter -LUDesignIDE, but seems all have it. Will file separate issue
