### ISSUE TITLE
Events from form don't called

### ISSUE THREAD

**Issue by cayque10** [andrea-magni/TFrameStand#75]
Hello. 
Thank you for the project, congratulations.

I have a doubt. Why event "OnShow" or "OnActivate" of form don't called after call LFormInfo.Show, only the "OnCreate"?
I took "FormStandHelloWord" as an exemple and went to debug to test.

```
procedure TMainForm.OpenButtonClick(Sender: TObject);
var
  LFormInfo: TFormInfo<TSecondForm>;
begin
  LFormInfo := FormStand1.GetFormInfo<TSecondForm>(True, Rectangle1);
  if not LFormInfo.IsVisible then
    LFormInfo.Show;
end;
```

Thank you.

**Comment by kabiri** [comment]
you can use attribiute [AfterShow]

    [AfterShow]
    procedure AfterShow;
