### ISSUE TITLE
hide or HideAndCloseAll

### ISSUE THREAD

**Issue by kabiri** [andrea-magni/TFrameStand#78]
Hello
what is difrent between CloseAll and HideAndCloseAll?

**Comment by andrea-magni** [comment]
Hi @kabiri ,
CloseAll method will destroy (Free) all active instances.
HideAndClose will destroy (Free) all active instances but before destroying each instance, it will call Hide method and wait it to complete (i.e. if there are OnHide animations, it will wait them to complete) before proceeding to destruction of the instance.

Hope this help, I do apologize for being so late.

Reopen the issue if something's unclear.

Sincerely,
Andrea
