### ISSUE TITLE
Error when I hide MaterialButtons on iOS

### ISSUE THREAD

**Issue by acarlomagno** [andrea-magni/TFrameStand#8]
Hi,
I tried your MaterialButtons demo, it's ok, but when I hide the buttons I receive this error "Argument out of range".

only in iOS and iOS emulator

regards
Antonello

**Comment by fredycc** [comment]
I am experiencing the same detail but with Android 4.4 & Delphi RX10.

**Comment by andrea-magni** [comment]
Is this issue still actual? Or may I close it?

**Comment by acarlomagno** [comment]
close
