### ISSUE TITLE
Not really an issue, but more a question

### ISSUE THREAD

**Issue by TerohsLab** [andrea-magni/TFrameStand#9]
In the "attached" example, shouldn't TForm1.FMyFrame get set to nil when you click the ca_closeframe button?

As you see in GetMyFrame it errors because while FMyFrame gets totally emptied .. it doesn't quite get set to nil.

I'm probably missing something.

Besides that awesome work on TFrameStand. Makes working for mobile so much more comfortable!

[Unit1.fmx.txt](https://github.com/andrea-magni/TFrameStand/files/45124/Unit1.fmx.txt)
[Unit1.pas.txt](https://github.com/andrea-magni/TFrameStand/files/45126/Unit1.pas.txt)
[Unit2.fmx.txt](https://github.com/andrea-magni/TFrameStand/files/45125/Unit2.fmx.txt)
[Unit2.pas.txt](https://github.com/andrea-magni/TFrameStand/files/45127/Unit2.pas.txt)

**Comment by andrea-magni** [comment]
Thanks for the kind words and sorry for the late, is your question still actual?
Maybe one of the latest fixes for ARC solves it.
Let me know please.
